language: java
dist: trusty
jdk: oraclejdk8

env:
    global:
        - secure: "C+jAr1xarMfPCYC5s34OXeJ2X5GW3FrZeTekguA1wJaN4ZvIcuKo8XZLRfgLNpxsm2GlifOz8ac/HR1n1i8lTotic+UDCdMR+LikY7pKD9yduzi5D6v1546/jp9B2n0IVYKzbauy+3v5isawKY0e+SoDYvklTy9BK24nOWYKzGGi8ujhm5OKxiwMljx9qEm5mnwFUVLxZPeavWB2pKrXnS+BN7YT60rzoWM1acHieBNcYgaz1NF8324ClPxMOb8dXjMvP19GQN/Heg51dtlvdlrJoA5xjzjwQmPKQSDHWDLWeaSS45oRDuhjlabaJ4OIvvxOItpTjorDZ4hkGfTuvIwnK29FWPIDLR6Ijz+CjXCGN/1MkmBU5JJzbkuf3eN/QwWVjm+VqOV0SlNxdWuTnOMV7KoUJj4ZUSyxJKZ8ZKs2X/USMAf8MlRAL4Xp2bQ5wdj/Ws+OXd42ffb3rxWgMSUSyMtoaPSVYJKjF3IyWnd9JU0REARvld08f49jAPYjO+hm5bcmF3Njc+pyP5GG5eFBMjwfdSAZ2QI2S90yDpQSDS4lXdqP/xt4n0gkqGtmFVhWSzEnUX3CQy7yRZhcIb3isqgSAfeof6AtVzJXegeseABaEWkeI7jAI1Q+zPwtTOcHHJpccAkjRja5QQtNkRO8/y/c72OotcMmKNXo1pQ="

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    on:
        branch: master
        tags: true #Deploying only on tagged builds
