language: java
dist: trusty
jdk: oraclejdk8
secure: "H5axvvBaHiHfeCCER0VAB+KM+9frKr5cBAtqy+QpIlsSp7oN4wayxxrfWM0ll1dw+Gv7Uzr7rgRQDWcM/ELf+7c9Wi9ug+jZjYcE5t9mYrB9m8GHnac7S4Hlsx29qDXVzAnYqZ3vIChCCr4odf76SEYqPFQ/KOCLA5Cd6aGrKoYn7jqBh3tFpIQ70TJvzbNR4tYBPeytcwVEioEegFGhxRpIzLqRCxzdwoaP3qO2/OO1BGWkzIKIiYpM6tuRTIH8n4SoPJ/pEXVkEdnf+NjLJQ6MvihcHYl+mD/O5VsqJp87CZlUVW8WHgW9tWAauTsTn8evV26kXCx/s940RYIddOj5T8QiLNCuZWtmnBIFdPGCVcI22SFEvfFEW7Bm1IjofV6dHVhNkjuilBFj7v3XPDXEAm99OEMckNftuEDsDVBctnDpA1b718nA1HB0u6Mge+5+NiV438/Xnge6aLu4+BQs0kLlHMyiQUvDYAsbn4AnK1tM0ICZ+ZnInPbi3ezIbjdfI8PgUUySOqcBjL7otlsBhZ7o1uDmZGiz12xEZCh0EVZD61ys1A/uVIrTGnSM8YUsRMOS/mNwYhe0opAB92F6d1aVo/tQsE/7H6Zkh3clC1xLdq/txO8z3CzVqXvmqYkCOX2amture5Ur3z11jqbXAetnEeGCJgJNvMgzcPI="

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  
deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    on:
        branch: master
        tags: true #Deploying only on tagged builds
